Udate email Regex MM-170
ong-bitcoin-argentina/DIDI-SSI-Mobile pull request #118
Opened 2021-03-29 17:04 UTC by fedelmar

Actualizar el Regex para la validación de email para que acepte también la especificación TLD del país ('.org.ar' o '.com.ar').

2021-03-29 19:41 UTC, MatiasOS commented on src/src/model/Validations.tsx
> +	isEmail: matchesRegex(/^([a-z0-9_\.-]+)@([\da-z\.-]+)\.([a-z\.]{2,6})$/),
De dónde sale esta regex? 
Deberíamos usar una ya validada, por ejemplo 
```
/^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/
``` 
en el spec de [html](https://html.spec.whatwg.org/multipage/input.html#email-state-(type=email))

2021-03-29 19:47 UTC, MatiasOS requested changes

2021-03-29 19:47 UTC, MatiasOS commented on src/src/model/Validations.tsx
> +	isEmail: matchesRegex(/^([a-z0-9_\.-]+)@([\da-z\.-]+)\.([a-z\.]{2,6})$/),
De dónde sale esta regex? Porque hace match con `matias.ar@gmail.com.` Notar el punto final
Deberíamos usar una ya validada, por ejemplo 
```
/^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/
``` 
en el spec de [html](https://html.spec.whatwg.org/multipage/input.html#email-state-(type=email))

2021-03-29 19:53 UTC, tomaslosada reviewed
Por lo que veo también coincide con **.@gmail.com.ar**, por lo que coincido con que habría que corregirla.

2021-03-29 19:54 UTC, tomaslosada requested changes
Hay que cambiar la RegEx po una más restrictiva.

2021-03-30 13:51 UTC, MatiasOS approved these changes
:+1:

2021-03-30 19:10 UTC, tomaslosada approved these changes
Perfecto!

2021-03-30 19:26 UTC, merged