[MM-588] Agregar soporte para share Request
ong-bitcoin-argentina/DIDI-SSI-Mobile pull request #133
Opened 2021-11-19 16:06 UTC by fedelmar

- Se crear un nuevo mensaje de alerta que indique que un emisor no agregó un ShareReq. 
- Se agrega spiner en el cambio entre paginas.
- Se arregla funcionalidad de botones de cambio de pagina.

2021-11-20 02:44 UTC, MatiasOS requested changes
Unos detalles y está listo!

2021-11-20 02:44 UTC, MatiasOS commented on src/src/presentation/dashboard/issuers/IssuersScreen.tsx
> +            <Modal
Estaría bueno mover el modal a otro archivo, así queda re utilizable

2021-11-20 02:44 UTC, MatiasOS commented on src/src/presentation/dashboard/issuers/IssuersScreen.tsx
> +        this.setState({
Usar **setState(state => { ....})** acá también

2021-11-20 02:44 UTC, MatiasOS commented on src/src/presentation/dashboard/issuers/IssuersScreen.tsx
> +        this.setState({ modalVisible: !this.state.modalVisible});
Cuando se va a cambiar el estado en base a un estado anterior, hay que usar **setState(state => { ....})**. Esto es porque al momento de cambiar el estado no se aseguro que **this.state.modalVisible** tenga el mismo valor que cuando se llamó.  
Este problema es más evidente en dispositivos de gama baja, con son los del user objetivo de la app.

2021-11-20 02:44 UTC, MatiasOS commented on src/src/presentation/dashboard/issuers/IssuersScreen.tsx
> +    onPress() {
Puede ser que este método no se esté usando?

2021-11-23 19:35 UTC, farpires approved these changes
todo bien

2021-11-23 20:03 UTC, MatiasOS approved these changes

2021-11-23 20:03 UTC, merged