Mm 591 incompatible versions warning
ong-bitcoin-argentina/DIDI-SSI-Mobile pull request #139
Opened 2021-11-29 20:18 UTC by farpires

*  Consultó al sdk creando funciones , para obtener los valores de la versión aidiVersión
*  Llamamos a las funciones en el componente SplashContent
* Verificamos la Versión obtenida del sdk, versu la versión de la aplicación descargada

https://user-images.githubusercontent.com/55299077/143936680-4f691f11-2b3d-4ee4-bc2d-5287fc204012.mp4

2021-11-30 15:39 UTC, MatiasOS requested changes
Me parece que el mensaje de advertencia está un poco corrido hacia la izquierda? Puede ser?

2021-11-30 15:39 UTC, MatiasOS commented on src/src/presentation/SplashContent.tsx
> +		this.setState({
Cuando una actualización depende del estado anterior, conviene usar la forma de setState que recibe una función updater. 

```javascript
this.setState((state, props) => ({
  modalVisible: !state.modalVisible,
});
```

2021-11-30 15:39 UTC, MatiasOS commented on src/src/presentation/SplashContent.tsx
> +			modalVisible: true,
porfa, seteá **modalVisible** como false por defecto para evitar glitches de visualización.

2021-11-30 15:39 UTC, MatiasOS commented on src/src/presentation/SplashContent.tsx
> +			aidiVersion: VERSION,
esta asignación inicial no la pongas porque es medio confusa. aidiVersion representa la versión que devuleve el server no?

2021-11-30 15:39 UTC, MatiasOS commented on src/src/presentation/SplashContent.tsx
> +						{this.state.aidiVersion !== VERSION ? <WarningModal
Esto que esté siempre, sin el la comparación.

2021-11-30 15:39 UTC, MatiasOS commented on src/src/presentation/SplashContent.tsx
> +			aidiVersion: `${await getAidiVersion()}`,
Acá, conviene directamete hacer

```javascript
async componentDidMount() {
  const aidiVersion = await getAidiVersion();
  const  modalVisible = aidiVersion !== VERSION;
  this.setState({
    aidiVersion.
    modalVisible,
  });
}
```

2021-11-30 15:39 UTC, MatiasOS commented on src/src/presentation/SplashContent.tsx
> +							message={"Actualiza la nueva version"}
Porfa, cambiá el mensaje por:
```
Hay una nueva versión de ai·di! Por favor actualizá la app desde Playstore para evitar inconvenientes"
```

2021-11-30 18:50 UTC, farpires commented on src/src/presentation/SplashContent.tsx
> +			aidiVersion: VERSION,
exacta solo que pongo por defecto la versión del dispositivo, y luego cuando se realiza el montaje, antes de renderizar se actualiza compara y la versión del server con la del dispositivo .

2021-11-30 19:18 UTC, MatiasOS requested changes
Revisar los import, hay variables que no se usan

2021-11-30 19:18 UTC, MatiasOS commented on src/src/presentation/SplashContent.tsx
> +		const { modalVisible } = this.state;
Hermoso <3

2021-11-30 19:18 UTC, MatiasOS commented on src/src/presentation/SplashContent.tsx
> +						{modalVisible ? <WarningModalVersion
El operador ternario no es necesario, directamente no se visualiza el modal porque modalVisible es false

2021-11-30 19:18 UTC, MatiasOS commented on src/src/presentation/SplashContent.tsx
> +			aidiVersion: VERSION,
Claro, pero no ganamos nada si le asignamos una valor y luego lo pisamos con otro en componentDidMount()

2021-11-30 19:18 UTC, MatiasOS commented on src/src/presentation/SplashContent.tsx
> +			aidiVersion: VERSION,
de todos modos no es necesario guardalo ya que no lo estamos leyendo en ningún lado

2021-11-30 19:18 UTC, MatiasOS commented on src/src/presentation/common/WarningModalVersion.tsx
> +        this.setState({
Este setState sucede lo mismo que con el otro. Hay que usar **setState((state)=> ... )**

2021-12-01 13:57 UTC, MatiasOS requested changes
Ahora lo vemos en una llamada y lo terminamos

2021-12-01 13:57 UTC, MatiasOS commented on src/src/services/internal/getVersion.ts
> +        return response.right.aidiVersion;
Debería ser **return right(response.right.aidiVersion)** no?

2021-12-01 13:57 UTC, MatiasOS commented on src/src/presentation/common/WarningModalVersion.tsx
> +        this.setState(() => ({
Esto sigue raro, debería ser
```javascript
this.setState((state) => ({
  modalVisibleState: !state.modalVisibleState,
})
```

2021-12-01 13:57 UTC, MatiasOS commented on src/src/presentation/common/WarningModalVersion.tsx
> +                                onPress={() => this.toggleModal()}
Esto se puede mejorar si queda como **onPress={this.toggleModal}**

2021-12-02 00:21 UTC, MatiasOS approved these changes

2021-12-02 00:23 UTC, merged