Vus 18 capture front implementacion
ong-bitcoin-argentina/DIDI-SSI-Mobile pull request #167
Opened 2022-02-15 21:26 UTC by farpires

repository name: DIDI-SSI-Mobile

-  reducer update and new feature to add front image

-  identification navigation

-  photo validation

-  new confirmation or non-confirmation navigation

sample video :
https://proyecto-didi.atlassian.net/browse/VUS-109

2022-02-16 14:48 UTC, fedelmar commented on src/src/presentation/dashboard/vuIdentity/IdentityNavigator.tsx
> +	VuIdentityID: {};
Falta ValidateID, del servicio que ya existe de renaper?

2022-02-16 15:43 UTC, farpires commented on src/src/presentation/dashboard/vuIdentity/IdentityNavigator.tsx
> +	VuIdentityID: {};
agregado

2022-02-16 15:52 UTC, fedelmar approved these changes, later dismissed

2022-02-21 18:47 UTC, MatiasOS requested changes
Se te pasaron unos console.log :))

2022-02-21 18:47 UTC, MatiasOS commented on src/src/presentation/dashboard/common/VuDidiCamera.tsx
> +		} else {
Este el no es necesario. Puede quedar como 
```typescript
if (typeof resultDisabled === "object" && this.props.cameraButtonDisabled !== false) {
	return VuDidiCamera.cameraButton(() => Alert.alert(resultDisabled.title, resultDisabled.text));
}
if (this.props.cameraButtonDisabled === false) {
	return VuDidiCamera.cameraButton(() => this.takePicture());
}
``
No entiendo bien el flujo, pero que pasa cuando cameraButtonDisabled es true y resultDisabled no es un objeto? Parece un problema con los condicionales, capaz se pueda simplificar esa lógica

2022-02-21 18:47 UTC, MatiasOS commented on src/src/presentation/dashboard/common/VuDidiCamera.tsx
> +			console.log("INGRESANDO BACKKKKKK");
:smiling_face_with_tear:

2022-02-21 18:47 UTC, MatiasOS commented on src/src/presentation/dashboard/vuIdentity/IdentityScreen.tsx
> +		console.log('ANTES DE AGREGAR ');
:scream:

2022-02-21 18:47 UTC, MatiasOS commented on src/src/presentation/dashboard/vuIdentity/IdentityScreen.tsx
> +		console.log('FINNN');
:scream:

2022-02-21 18:47 UTC, MatiasOS commented on src/src/presentation/dashboard/vuIdentity/IdentityScreen.tsx
> +		console.log(result);
:scream:

2022-02-21 18:47 UTC, MatiasOS commented on src/src/presentation/dashboard/vuIdentity/VuIdentityBack.tsx
> +        console.log(await store.getState());
:scream_cat:

2022-02-21 18:47 UTC, MatiasOS commented on src/src/presentation/dashboard/vuIdentity/VuIdentityBack.tsx
> +        console.log(this.state);
:scream_cat:

2022-02-21 18:47 UTC, MatiasOS commented on src/src/presentation/dashboard/vuIdentity/VuIdentityBack.tsx
> +        console.log(this.props);
:scream_cat:

2022-02-21 18:47 UTC, MatiasOS commented on src/src/presentation/dashboard/vuIdentity/VuIdentityTakePhoto.tsx
> +			console.log(this.state.state);
:walking_man:  :gun:

2022-02-21 19:58 UTC, farpires commented on src/src/presentation/dashboard/common/VuDidiCamera.tsx
> +		} else {
si, se utiliza un prop con dos posibles tipos de valores un objeto o un boolean, de esta manera logró manipular el escaneo del carnet en tiempo real

2022-02-23 21:07 UTC, MatiasOS approved these changes

2022-02-24 00:00 UTC, fedelmar approved these changes

2022-02-24 16:19 UTC, merged