Vus 171 connect new enpoint implementation
ong-bitcoin-argentina/DIDI-SSI-Mobile pull request #174
Opened 2022-03-28 14:56 UTC by farpires

DIDI-SSI-Mobile:

-  getInformation function implementation
- screen title and subtitle information
- vuSecurity Data Captures
- typescript models

https://proyecto-didi.atlassian.net/jira/software/c/projects/VUS/boards/12?selectedIssue=VUS-171

2022-03-28 21:56 UTC, MatiasOS requested changes
Unos pequeños cambios, el resto parece estar bien

2022-03-28 21:56 UTC, MatiasOS commented on src/src/presentation/resources/strings.ts
> +			congrats: "Se enviarán los siguientes datos a validar por ReNaPer:",
Se enviarán los siguientes datos a validar por VU Security

2022-03-28 21:56 UTC, MatiasOS commented on src/src/presentation/resources/strings.ts
> +			congrats: "¡Felicitaciones! Su identidad ha sido validada.",
¡Felicitaciones! Tu identidad ha sido validada.

2022-03-28 21:56 UTC, MatiasOS commented on src/src/presentation/resources/strings.ts
> +			reminder: "Recuerda que tus datos son privados y no serán compartidos.",
Recordá que tus datos son privados y no serán compartidos.

2022-03-28 21:56 UTC, MatiasOS commented on src/src/presentation/resources/strings.ts
> +			congrats: "Su identidad no ha sido validada. Por favor, vuelva a intentar.",
Tu identidad no ha sido validada. Por favor, vuelva a intentar.

2022-03-28 21:56 UTC, MatiasOS commented on src/src/presentation/dashboard/vuIdentity/VuIdentitySubmitScreen.tsx
> +	dataCorrection = (documentDataVu : IReturnGetInformation): IDocumentData =>{
Mejor renombrar como **flatGetInfomationResponse**, o **mapGetInfomationResponse**

2022-03-30 13:46 UTC, fedelmar submitted a review, later dismissed

2022-03-31 22:42 UTC, MatiasOS approved these changes
Gracias por subir el video!

2022-04-01 18:17 UTC, merged